module Cure
  module Orchestrator
    module Models
      class Job
        def self.all_with_runs: -> Array[Hash[Symbol, Object]]
        def self.next_pending_job: -> Job

        def update_status: -> Job
        def mark_complete: -> void
        def mark_error: (String, String) -> void
      end
    end
  end
end
