#!/usr/bin/env ruby

require "sequel"
require "json"

config_file_location = "/etc/cure/config.json"

unless File.exist? config_file_location
  raise "No config file located at #{config_file_location}. Please run init-setup first."
end

config = JSON.parse(File.read(config_file_location))

DATABASE = Sequel.sqlite(config["database_file_location"])

unless DATABASE.table_exists? :jobs
  DATABASE.create_table :jobs do
    primary_key :id
    String :name
    String :template_file, null: false
    String :input_file, null: false
    String :status, null: false
    Integer :error_count, null: false, default: 0
    String :last_error_message
    DateTime :created_at, default: Sequel::CURRENT_TIMESTAMP, index: true
    DateTime :updated_at
  end
end

unless DATABASE.table_exists? :job_runs
  DATABASE.create_table :job_runs do
    primary_key :id
    foreign_key :job_id, :jobs
    String :status, null: false
    String :error_message
    DateTime :created_at, default: Sequel::CURRENT_TIMESTAMP, index: true
    DateTime :updated_at
  end
end
