module Cure
  module Processor
    class Server
      @config: Hash[Symbol, Object]
      @database: untyped
      @database_mutex: Thread::Mutex
      @pids: Array[Integer]
      @pids_mutex: Thread::Mutex

      def start: -> void

      private

      def boot_init: -> void

      def database_mutex: -> Thread::Mutex

      def pids_mutex: -> Thread::Mutex

      # How do i return a class?
      def retrieve_job: -> (nil | Orchestrator::Models::Job)

      def shut_down: -> void
    end
  end
end
