module Cure
  module Orchestrator
    module Routes
      class BaseRoute

        attr_reader request: untyped

        def call: -> Hash[Symbol, Object]

        private

        def parsed_request: -> Hash[String, Object]
      end
    end
  end
end
